### PR TITLE
Add shadow components to starter

### PR DESCRIPTION
**Pull request by jxnblk**
Adds shadow components to the starter to serve as a starting point for adding custom components and customizing built-in components

### CODE REVIEW

**Comment by thinkybeast** [comment]
I like the direction of this so far; I wonder whether the new component the starter adds should be something the Starter actually uses (e.g. should we make the SuperHero functionally/aesthetically different and use it on the landing page? should we use a different component as an example?)

**Comment by jxnblk** [comment]
Yeah, was wondering the same thing. Since the demo content is only used in the starter and the theme doesn't need to be tied to it, we _could_ add it to the content model and show it being used. As far as what that should look like vs the default Hero, was thinking it might make sense to do a centered/stacked layout, but given the data structure, it might make more sense to have an example component that doesn't need to parse the data to pluck out things like the hero image

**Review by thinkybeast — APPROVED** [review]
🚢

**Comment by jxnblk** [comment]
Going to ship what's here for now, but do think there's room for improvement for the two component examples in the starter

**Pull request merged**
